import { faq, sliderContent } from "@/constants/const";
import Head from "next/head";
import Slider from "react-slick";
import Body from "./Body";
import CountUp from "react-countup";
import client1 from "../../public/assets/images/client1.png";
import client2 from "../../public/assets/images/client2.jpeg";
import { BiHappyHeartEyes } from "react-icons/bi";
import { FaAward, FaRegAddressBook, FaRegClock } from "react-icons/fa";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Link from "next/link";
import { useState } from "react";
import { FiChevronDown, FiChevronUp } from "react-icons/fi";
import Accordion from "@/Components/Accordion";
export default function Home() {
  var settings = {
    dots: true,
    autoplay: true,
    speed: 1500,
    slidesToShow: 1,
    slidesToScroll: 1,
    infinite: true,
  };

  var ClientSettings = {
    autoplay: true,
    speed: 500,
    slidesToShow: 5,
    slidesToScroll: 1,
    infinite: true,
  };

  return (
    <>
      <Head>
        <title>High Quality</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <section id="hero-area" className="bg-blue-100 ">
          <div className="">
            <Slider {...settings}>
              {sliderContent.map((item, index) => (
                <div className="" key={index}>
                  <div
                    className="p-4 flex items-center justify-start"
                    style={{
                      backgroundImage: `url(${item?.image?.src})`,
                      width: "100%",
                      height: "450px",
                      backgroundRepeat: "no-repeat",
                      backgroundSize: "cover",
                      backgroundPosition: "center",
                    }}
                  >
                    {/* <div className="md:container  flex items-start justify-start flex-col text-left">
                      <h3 className="md:text-5xl text-3xl primary ">
                        {item.heading}
                      </h3>
                      <h2 className="text-2xl my-4 font-semibold text-gray-600">
                        {item.content}
                      </h2>

                      <div className="flex flex-col md:flex-row gap-4">
                        <a className="btn mr-4 sm:mb-0" href="#services">
                          Our Services
                        </a>

                        <a
                          className="btn-alt"
                          type="button"
                          href={"assets/files/profile.pdf"}
                          download={"Aarotech_Profile.pdf"}
                          onClick={(e) => e.stopPropagation()}
                        >
                          Our Profile
                        </a>
                      </div>
                    </div> */}
                  </div>
                </div>
              ))}
            </Slider>
          </div>
        </section>
        <section id="about" className="about my-12">
          <div className="container mx-auto sm:px-4">
            <p className="heading">Our Achivements</p>

            <div className="flex flex-wrap  mt-5 md:my-12">
              <Card
                icon={<BiHappyHeartEyes className="text-gray-400 text-6xl" />}
                duration={200}
                title={"Happy Clients"}
              />
              <Card
                icon={<FaRegAddressBook className="text-gray-400 text-6xl" />}
                duration={15}
                title={"Countries"}
              />
              <Card
                icon={<FaRegClock className="text-gray-400 text-6xl" />}
                duration={12}
                title={"Years experience"}
              />
              <Card
                icon={<FaAward className="text-gray-400 text-6xl" />}
                duration={8}
                title={"Countries Linked"}
              />
            </div>
          </div>
        </section>
        <section id="md" className="bg-primary text-white">
          <div className="container mx-auto py-10">
            <div className="grid grid-cols-3 gap-12 items-center">
              <div className="col-span-3 md:col-span-1">
                <img
                  src="/assets/images/md.jpg"
                  alt=""
                  className="rounded-full object-cover h-[500px] w-[500px]"
                />
              </div>
              <div className="col-span-3 md:col-span-2">
                <p className="text-5xl mb-4">Message from MD</p>
                <p className="text-lg leading-relaxed">
                  Dear Valued Clients, <br /> <br /> It is with pride that I
                  welcome you at High Quality Overseas Pvt. Ltd. We strive our
                  best to satisfy the needs of both our customers and clients.
                  We constantly improve on our existing services to respond to
                  your ever-changing needs. Our team comprises of highly
                  qualified and experienced associates who possess all the
                  required resources to assist you to the best of their
                  abilities. We have trained career counselors who are well
                  placed to provide career related advice and information to
                  interested candidates. We have a highly detailed and
                  systematic data bank, which is of utmost importance to job
                  seekers as well as employers. <br /> <br /> We shall continue
                  to provide outstanding and quality service. We thank our
                  valued prospective clients for trusting us and believing in
                  our capabilities. And as our motto states, we really are only
                  obsessed with quality!!!
                </p>
              </div>
            </div>
          </div>
        </section>

        <section id="clients" className="my-12">
          <div className="container mx-auto">
            <p className="heading my-8 mb-12">Our Clients</p>

            <Slider {...ClientSettings}>
              {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].map((item) => (
                <img
                  src={`/assets/images/clients/client (${item + 1}).png`}
                  alt=""
                  className="h-[250px] object-contain  my-8 pr-6"
                  key={item}
                />
              ))}
            </Slider>
          </div>
          <Link href="/clients">
            <div className="outlined-button">View All</div>
          </Link>
        </section>
        <section id="faq" className="my-12 md:my-32">
          <div className="container mx-auto">
            <p className="heading my-8 mb-12">Frequently Asked Questions</p>
            <div className="mt-20">
              {faq.map(({ quest, ans }) => (
                <Accordion quest={quest} ans={ans} key={ans} />
              ))}
            </div>
          </div>
        </section>
      </Body>
    </>
  );
}
export const Card = ({ icon, duration, title }) => {
  return (
    <div className="lg:w-1/4 md:w-1/2 sm:w-full pr-4 pl-4">
      <div className="py-8 rounded-lg shadow-lg border">
        <div className="flex-center justify-center gap-8">
          {icon}
          <div className="flex flex-col justify-center items-center">
            <div className="center gap-4">
              <CountUp
                end={duration}
                duration={5}
                suffix="+"
                className="text-4xl primary font-semibold"
              ></CountUp>
              {/* <FaSmile className="text-yellow-400 text-4xl" /> */}
            </div>
            <p className="font-semibold my-2 leading-8 text-2xl text-gray-600 ">
              {title}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
